cuneiform/items/forms.py
# forms.py items
from cuneiform.models import Item
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    IntegerField,
    SubmitField,
    BooleanField,
    ValidationError,
)
from wtforms.validators import InputRequired, DataRequired, Length
from flask_login import current_user
from flask_wtf.file import FileField, FileAllowed, FileRequired
from flask_uploads import UploadSet, IMAGES


class AddForm(FlaskForm):

    min, max = Item.name_min_len, Item.name_max_len
    name = StringField(
        "Name of Item:",
        validators=[
            InputRequired(message="Name required"),
            Length(
                min=min,
                max=max,
                message=f"Name must be between {min} \
                                            and {max} characters",
            ),
        ],
    )

    submit = SubmitField("Add Item")


class UpdateForm(FlaskForm):

    # following field is hidden in the template
    id = IntegerField("Id of Item to Buy:", validators=[DataRequired()])
    min, max = Item.name_min_len, Item.name_max_len
    name = StringField(
        "Name of Item:",
        validators=[
            InputRequired(message="Name required"),
            Length(
                min=min,
                max=max,
                message=f"Name must be between {min} and {max} characters",
            ),
        ],
    )
    is_bought = BooleanField("Is Bought", default="checked")
    submit = SubmitField("Update")

    def validate_id(self, field):
        id = field.data
        user = current_user
        item = Item.query.filter_by(id=id).first()

        if not item or item.user_id != user.id:
            print("cannot edit this item")
            raise ValidationError("Cannot edit this item")

        print(f"user id {user.id}, item id {item.id}")


images = UploadSet("images", IMAGES)


class UploadForm(FlaskForm):
    image = FileField(
        "Image",
        validators=[
            FileRequired(),
            FileAllowed(
                ["jpg", "png", "jpeg"], "Images only (png, jpg and jpeg extensions)!"
            ),
        ],
    )

cuneiform/items/__init__.py
"""
The users Blueprint handles the user management for this application.
Specifically, this Blueprint allows for new users to register and for
users to log in and to log out of the application.
"""
from flask import Blueprint
items_blueprint = Blueprint('items', __name__,
                            template_folder='templates')

from . import views

cuneiform/items/views.py
# cuneiform/users/items.py

from flask import render_template, redirect, url_for, request, flash
from cuneiform import db
from cuneiform.models import Item, User
from cuneiform.items.forms import AddForm, UpdateForm, UploadForm
from flask_login import current_user, login_required
from . import items_blueprint
from flask_uploads import configure_uploads, IMAGES, UploadSet
from cuneiform.services.ocrservice import OcrService
import requests
from flask_injector import FlaskInjector
from injector import inject
from cuneiform.dependencies import configure

# from ocrservice import worker

# work around for providing user feedback, as CSS modal fade class
# doesn't display the raised validation errors
def flash_errors(form):
    """Flashes form errors"""
    for errors in form.errors.items():
        for error in errors:
            flash(f"Error: {error}")


# GET /items/create
@items_blueprint.route("/create", methods=["GET"])
@login_required
def create():
    form = AddForm()
    return render_template("add_item.html.j2", form=form)


# POST /items
@items_blueprint.route("", methods=["POST"])
@login_required
def store():

    add_form = AddForm()
    if add_form.validate_on_submit():
        name = request.form["name"]
        user_id = current_user.id
        # Add new item to database
        new_item = Item(name, user_id)
        db.session.add(new_item)
        db.session.commit()

    flash_errors(add_form)

    return redirect(url_for("items.index"))


# POST /items/shoppinglist
@inject
@items_blueprint.route("/shoppinglist", methods=["POST"])
@login_required
def store_many(service: OcrService):

    upload_form = UploadForm()
    if upload_form.validate_on_submit():
        image_file = upload_form.image.data
        image = image_file.read()
        items_list, err_code = service.process_image(image)

        if items_list == None:
            # Could not process the image, flash specific err_code
            flash(service.err_code_to_message.get(err_code))
            return redirect(url_for("items.index"))

        user_id = current_user.id

        for item in items_list:
            name = item
            new_item = Item(name, user_id)
            db.session.add(new_item)
            db.session.commit()

        return redirect(url_for("items.index"))

    flash_errors(upload_form)

    return redirect(url_for("items.index"))  # image not provided


# GET items
@items_blueprint.route("", methods=["GET"])
@login_required
def index():

    add_form = AddForm()
    update_form = UpdateForm()
    upload_form = UploadForm()
    # Grab a list of items from database.
    items = (
        db.session.query(User, Item)
        .filter(
            User.id == Item.user_id,
            Item.user_id == current_user.id,
            Item.is_bought == False,
        )
        .all()
    )
    return render_template(
        "items/items_list.html.j2",
        items=items,
        add_form=add_form,
        update_form=update_form,
        upload_form=upload_form,
    )


# GET ITEMS/shoppinglist
@items_blueprint.route("/shoppinglist", methods=["GET"])
@login_required
def purchases():
    # Grab a list of items from database.
    items = (
        db.session.query(User, Item)
        .filter(
            User.id == Item.user_id,
            Item.user_id == current_user.id,
            Item.is_bought == True,
        )
        .all()
    )
    return render_template("items/purchases_list.html.j2", items=items)


# GET /items/<id>/edit form
@items_blueprint.route("/<id>/edit", methods=["GET"])
@login_required
def edit(id):
    item = Item.query.get(id)
    form = UpdateForm()
    return render_template("buy_items.html.j2", form=form, item=item)


# /items/<id>
@items_blueprint.route("/<id>/update", methods=["POST"])
@login_required
def update(id):

    update_form = UpdateForm()
    item = Item.query.get(id)

    if update_form.validate_on_submit():
        item.name = request.form["name"]
        item.is_bought = bool(request.form["is_bought"])
        flash("Item Status Updated Successfully")
        db.session.commit()

    flash_errors(update_form)

    return redirect(url_for("items.index"))

cuneiform/items/templates/items/items_list.html.j2
{% extends 'base.html.j2' %}
{% from 'field_macro.html.j2' import render_field %}
{% block title %} This weeks list {% endblock %}


{% block content %}

<div class="container">
  <div class="row">
    <div class="col md-12">
      <div class="d-block p-2 bg-light">
        <h2>Manage
          <b>Items</b>
          <button type="button"  class="btn btn-success float-right" data-bs-toggle="modal" data-bs-target="#mymodal">
            Add New Items
          </button>
          <button type="button"  class="btn btn-success float-right" data-bs-toggle="modal" data-bs-target="#mymodal2">
            Upload Image
          </button>
        </h2>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success alert-dismissable" role="alert">
            <button type="button" class="close" data-bs-dismiss="alert" aria-label="close">
              <span aria-hidden="true">x</span>
            </button>
        {{message}}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <table class="table table-hover table-dark">
          <div class="table-responsive">
            <table class = "table align-middle">
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Is Bought</th>
                <th>Requested By</th>
                <th>Action</th>
              </tr>
              {% for user,item in items %}
              <tr>
                <td>{{item.id}}</td>
                <td>{{item.name}}</td>
                <td>{{item.is_bought}}</td>
                <td>{{user.username}}</td>
                <td>
                  <div class="d-flex">
                    <a href="#" class="btn btn-warning btn-xs me-3" data-bs-toggle="modal" data-bs-target="#modaledit{{item.id}}">Edit</a>

                      <form action="{{url_for('items.update',id=item.id)}}" method="POST">
                        {# This hidden_tag is a CSRF security feature. #}
                        {{ update_form.hidden_tag() }}
                        <div class="form-group">
                          {{ update_form.id(value=item.id, type="hidden")}}
                          {{ update_form.name(value=item.name, type="hidden") }}
                          {{ update_form.is_bought(type="hidden")}}
                          {{ update_form.submit(class="btn btn-danger btn-xs",
                            onclick="return confirm('Mark as bought and move to purchased?')" ,
                            value="Mark as Bought")}}
                        </div>
                      </form>
                    </div>

                </td>
              </tr>

              <div class="modal fade" id="modaledit{{item.id}}" data-bs-backdrop="static" role="dialog">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h4 class="modal-title">Update Information</h4>
                    </div>
                    <div class="modal-body">
                      <form action="{{url_for('items.update',id=item.id)}}" method="POST">
                        {# This hidden_tag is a CSRF security feature. #}
                        {{ update_form.hidden_tag() }}
                        <div class="form-group">
                          {{ update_form.id(value=item.id, type="hidden")}}
                          {{ update_form.is_bought(value=false, type="hidden")}}
                          {{ update_form.name.label }} {{ update_form.name(class="form-control",value=item.name) }}
                        </div>
                        <div class="form-group">
                          {{ update_form.submit(class="btn btn-primary") }}
                        </div>
                      </form>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </table>
          </div>
        </table>
      </div>


      <div id="mymodal" class="modal fade" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Add Item</h4>
            </div>
            <div class="modal-body">
              <form action="{{url_for('items.store')}}" method="POST">
                {# This hidden_tag is a CSRF security feature. #}
                {{ add_form.hidden_tag() }}
                <div class="form-group">
                  {{ add_form.name.label }} {{ add_form.name(class="form-control")}}
                </div>
                <div class="form-group">
                  {{add_form.submit(class="btn btn-primary")}}
                </div>
              </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

      <div id="mymodal2" class="modal fade" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Upload List</h4>
            </div>
            <div class="modal-body">
              <form action="{{url_for('items.store_many')}}" method="POST" enctype="multipart/form-data">
                {# This hidden_tag is a CSRF security feature. #}
                {{ upload_form.hidden_tag() }}
                <div class="form-group">
                  {{ upload_form.image(class="form-control")}}
                </div>
                <div class="form-group">
                  <button type="submit" class="btn btn-primary">Upload</button>
                </div>
              </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>


{% endblock %}

cuneiform/items/templates/items/purchases_list.html.j2
{% extends 'base.html.j2' %}
{% from 'field_macro.html.j2' import render_field %}
{% block title %} This weeks list {% endblock %}


{% block content %}

<div class="container">
  <div class="row">
    <div class="col md-12">
      <div class="d-block p-2 bg-light">
        <h2>Manage
          <b>Purchases</b>
        </h2>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success alert-dismissable" role="alert">
            <button type="button" class="close" data-bs-dismiss="alert" aria-label="close">
              <span aria-hidden="true">x</span>
            </button>
        {{message}}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <table class="table table-hover table-dark">
          <div class="table-responsive">
            <table class = "table align-middle">
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Is Bought</th>
                <th>Requested By</th>
              </tr>
              {% for user,item in items %}
              <tr>
                <td>{{item.id}}</td>
                <td>{{item.name}}</td>
                <td>{{item.is_bought}}</td>
                <td>{{user.username}}</td>
                <td>
                </td>
              </tr>
              {% endfor %}
            </table>
          </div>
        </table>
      </div>
    </div>
  </div>
</div>


{% endblock %}